name:                eh
version:             0.1.0.0
github:              "urxvtcd/eh"
license:             BSD3
author:              "Marcin Charęza"
maintainer:          "mc@surd.us"
copyright:           "2019 Marcin Charęza"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            eh, an ed editor clone
category:            Editor

description:         Toy project. Refer to the README.md in the repository.

dependencies:
- base >= 4.7 && < 5
- hspec >= 2.7 && < 3
- mtl >= 2.2.2 && < 3
- containers
- haskeline

library:
  source-dirs: src
  ghc-options:
  - -Weverything
  - -Werror
  - -Wno-safe
  - -Wno-unsafe
  - -Wno-implicit-prelude
  - -Wno-missing-exported-signatures

  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

executables:
  eh:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Weverything
    - -Werror
    - -Wno-safe
    - -Wno-unsafe
    - -Wno-implicit-prelude
    - -Wno-missing-exported-signatures

    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - eh

tests:
  eh-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Weverything
    - -Werror
    - -Wno-safe
    - -Wno-unsafe
    - -Wno-implicit-prelude
    - -Wno-missing-exported-signatures
    - -Wno-missing-import-lists
    - -Wno-missing-export-lists
    - -Wno-all-missed-specialisations

    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - eh

default-extensions:
  - UnicodeSyntax
  - MultiParamTypeClasses
